### ISSUE TITLE
Upload TXT into Playbook itself

### ISSUE THREAD

**Issue by moocow1452** [IdreesInc/PlayBook#6]
This is probably very of scope, but I've been having trouble side loading txt files into the Playdate over USB, in that the Playbook app doesn't recognize them. Would it be possible to have something similar to Share to Kindle or the official Playdate side loading portal where TXT files could be uploaded, then built into a PDX file that a user could then sideload? If you wanted to be super ambitious, you could have it do some server side conversation for other files or pull RSS feeds or something wild, but I wanted to know if that was anywhere near your wheelhouse.

**Comment by IdreesInc** [comment]
Hm, maybe? You'd need a script that could be run on a computer to bundle the book files into the pdx, and then the pdx would need to be sideloaded. From there you would run the sideloaded app and have that put the book files into the shared folder that is currently being experimented with in the Playdate SDK. Lastly, the PlayBook app would need to read from that folder and move the books into the local app space. Bit convoluted, but if enough people request it, maybe I'd give it a shot.

**Comment by IdreesInc** [comment]
Wait, what do you mean the app isn't recognizing your txt files? Mind sharing them here?

**Comment by moocow1452** [comment]
Was sideloading into Games/Playbook, not Data/Playbook. Apologies, reading is hard.
